# Generated by Django 5.2.6 on 2025-11-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('service', models.CharField(choices=[('Boarding', 'Boarding'), ('Grooming', 'Grooming'), ('Play Time', 'Play Time'), ('Curated Meals', 'Curated Meals'), ('Training', 'Fitness & Training'), ('Massage', 'Massages & Physio'), ('Coffee Bar', 'Pet People Coffee Bar'), ('Working Space', 'Working Space'), ('Add-ons', 'Add-ons')], max_length=50)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('message', models.TextField(blank=True, null=True)),
                ('consent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
