# Generated by Django 5.2.6 on 2025-11-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pet_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('service', models.CharField(choices=[('Boarding', 'Boarding 🏠'), ('Grooming', 'Grooming ✂️'), ('Play Time', 'Play Time 🏊\u200d♂️'), ('Meals', 'Curated Meals 🍲'), ('Training', 'Fitness & Training 🐕'), ('Massage', 'Massages & Physio'), ('Coffee', 'Coffee Bar ☕'), ('Workspace', 'Working Space 💻'), ('Add-ons', 'Add-ons ➕')], max_length=50)),
                ('fee', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('consent', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='ServiceBooking',
        ),
    ]
