# Generated by Django 5.2.6 on 2025-10-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Upload a featured image for this post', null=True, upload_to='blog_images/'),
        ),
    ]
